from typing import Any

class MqttError(Exception): ...

class MqttCodeError(MqttError):
    rc: int = ...
    def __init__(self, rc: int, *args: Any) -> None: ...

class MqttConnectError(MqttCodeError):
    def __init__(self, rc: int) -> None: ...
