blank_issues_enabled: false
contact_links:
  - name: GitHub discussions
    url: https://github.com/empicano/aiomqtt/discussions
    about: Ask (and answer) questions, brainstorm, and show what you've built.
