#!/usr/bin/env bash

# Safety first
set -o errexit -o pipefail -o nounset
# Change into the project's directory
cd "$(dirname "$0")/.."

# Check with ruff and mypy
poetry run ruff check asyncio_mqtt tests
poetry run mypy asyncio_mqtt tests
