#!/usr/bin/env bash

# Safety first
set -o errexit -o pipefail -o nounset
# Change into the project's directory
cd "$(dirname "$0")/.."

# Start Mosquitto with Docker
docker run -it --rm --name mosquitto \
  -p 127.0.0.1:1883:1883 \
  -p 127.0.0.1:8080:8080 \
  -p 127.0.0.1:8883:8883 \
  -p 127.0.0.1:1884:1884 \
  -v "$(pwd)/scripts/mosquitto.conf:/mosquitto/config/mosquitto.conf" \
  -v "$(pwd)/scripts/mosquitto.passwd:/mosquitto/config/mosquitto.passwd" \
  -v "$(pwd)/scripts/mosquitto.crt:/mosquitto/certs/mosquitto.crt" \
  -v "$(pwd)/scripts/mosquitto.key:/mosquitto/certs/mosquitto.key" \
  eclipse-mosquitto:latest
