#!/usr/bin/env bash

# Safety first
set -o errexit -o pipefail -o nounset
# Change into the project's directory
cd "$(dirname "$0")/.."

# Run tests with pytest
poetry run pytest --failed-first --strict-config --strict-markers --verbosity=2 --cov=asyncio_mqtt --cov-report=xml --junitxml=reports/pytest.xml tests
