name: docs

on:
  push:
    branches: [main, poetry-and-rename]
    paths:
      - "docs/**"
      - README.md
      - .github/workflows/docs.yml
  pull_request:
    paths:
      - "docs/**"
      - README.md
      - .github/workflows/docs.yml

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4 # Uses the Python version in the .python-version file
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.4.2"
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: scripts/setup
      - name: Build documentation
        run: poetry run sphinx-build -b html docs docs/_build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          publish_branch: documentation
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
