name: Build documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - README.md
      - .github/workflows/docs.yml
  pull_request:
    paths:
      - "docs/**"
      - README.md
      - .github/workflows/docs.yml

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Set up Python
        uses: actions/setup-python@v4 # Uses the Python version in .python-version
        with:
          cache: "poetry"
      - name: Install dependencies
        run: scripts/setup
      - name: Build documentation
        run: scripts/docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          publish_branch: documentation
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
